# example travis.yml haxe configuration
language: objective-c # change this to c to test on a linux machine
env:
  global:
    - OS=mac # add this too to let the script know that the OS is a mac
      # REMOTE_SHARED
    - secure: "bE3EqReyQFIQmMXQDEX/mgRbh+vzqDTzF6RMynjXaTUI9TsPTAwywwRLC7c+WpPfoidRnNnXLK8Qplde5wip1tliLvfaBErMkk8m9MmHUpfrAnLnqN2gqeAtTHbx5yhy+VV0XzIRDvcqq6Fw0XI92o5+twF24qv9Q+23R2sgLb8="
      # REMOTE_ARGS
    - secure: "qag9oZXj5E4TJ03VCyoY230Qaree3YxvFXZo609DsOYxtEwLG+luFAiV8YKxAdTimWFMXwGrpoEp4j+sWWTiwBgz35On6awUd34CBNs5t/DZZna9MJgrLpQQMwzY7yUm0Eof2U3dLLddmUpnlRA9O819mMkbIBh+5gKFCPkPohE="
  matrix:
    - TARGET=cs DEVICE=desktop
    - TARGET=cs DEVICE=ios

matrix:
  fast_finish: true
  allow_failures:
    - env: TARGET=cs DEVICE=ios

before_install: # clone travis-hx repo
  - travis_retry git clone --depth=50 --branch=master git://github.com/waneck/travis-hx.git ~/travis-hx

install: # setup the target
  - ~/travis-hx/setup.sh
  - haxelib install utest
  - haxelib install mcli
  - haxelib dev unihx "$TRAVIS_BUILD_DIR"

script:
  - cd $TRAVIS_BUILD_DIR/tests
  - ./run-travis.sh
