clone_folder: c:\projects\unihx

environment:
  matrix:
    - TARGET: cs

install: # clone travis-hx repo and setup the target
  - git clone --depth=50 --branch=master git://github.com/waneck/travis-hx.git C:\travis-hx
  - C:\travis-hx\extra\appveyor\AppVeyor.exe setup
  - SET PATH=c:\HaxeToolkit\haxe;C:\HaxeToolkit\neko;C:\Program Files\7-Zip\;%PATH%
  - haxelib install utest
  - haxelib dev unihx C:\projects\unihx
  - cinst wget -x86

build_script:
  - cd \projects\unihx\tests
  - haxe build.hxml
  - bin\bin\CmdTests-Debug.exe
